name: ROS 2 CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble
      - uses: ros-tooling/action-ros-ci@v0.4
        with:
          package-name: planner_interfaces unordered_task_planner grid_motion_planner planner_bringup
          target-ros2-distro: humble
